batch_size: 256
clip_gradient_norm: 1
clip_targets_to_zero:
- streamflow
commit_hash: e4329c3
data_dir: ..\..\data\american_river_camels
dataset: caravan
device: cpu
dynamic_inputs:
- snow_depth_water_equivalent_mean
- surface_net_solar_radiation_mean
- surface_net_thermal_radiation_mean
- surface_pressure_mean
- temperature_2m_mean
- dewpoint_temperature_2m_mean
- u_component_of_wind_10m_mean
- v_component_of_wind_10m_mean
- volumetric_soil_water_layer_1_mean
- volumetric_soil_water_layer_2_mean
- volumetric_soil_water_layer_3_mean
- volumetric_soil_water_layer_4_mean
- snow_depth_water_equivalent_min
- surface_net_solar_radiation_min
- surface_net_thermal_radiation_min
- surface_pressure_min
- temperature_2m_min
- dewpoint_temperature_2m_min
- u_component_of_wind_10m_min
- v_component_of_wind_10m_min
- volumetric_soil_water_layer_1_min
- volumetric_soil_water_layer_2_min
- volumetric_soil_water_layer_3_min
- volumetric_soil_water_layer_4_min
- snow_depth_water_equivalent_max
- surface_net_solar_radiation_max
- surface_net_thermal_radiation_max
- surface_pressure_max
- temperature_2m_max
- dewpoint_temperature_2m_max
- u_component_of_wind_10m_max
- v_component_of_wind_10m_max
- volumetric_soil_water_layer_1_max
- volumetric_soil_water_layer_2_max
- volumetric_soil_water_layer_3_max
- volumetric_soil_water_layer_4_max
- total_precipitation_sum
- potential_evaporation_sum
epochs: 50
experiment_name: american_river_test_run
head: regression
hidden_size: 20
img_log_dir: 
  c:\Users\Inigo\Projects\neuralhydrology\examples\01-Introduction\runs\american_river_test_run_1806_105745\img_log
initial_forget_bias: 3
learning_rate:
  0: 0.01
  30: 0.005
  40: 0.001
log_interval: 5
log_n_figures: 1
log_tensorboard: true
loss: MSE
metrics:
- NSE
model: cudalstm
num_workers: 8
number_of_basins: 1
optimizer: Adam
output_activation: linear
output_dropout: 0.4
package_version: 1.10.0
predict_last_n: 1
run_dir: 
  c:\Users\Inigo\Projects\neuralhydrology\examples\01-Introduction\runs\american_river_test_run_1806_105745
save_weights_every: 1
seed: 706171
seq_length: 365
target_variables:
- streamflow
test_basin_file: 2_basin.txt
test_end_date: 31/12/2017
test_start_date: 01/01/2007
train_basin_file: 2_basin.txt
train_dir: 
  c:\Users\Inigo\Projects\neuralhydrology\examples\01-Introduction\runs\american_river_test_run_1806_105745\train_data
train_end_date: 31/12/1993
train_start_date: 01/01/1950
validate_every: 3
validate_n_random_basins: 1
validation_basin_file: 2_basin.txt
validation_end_date: 31/12/2006
validation_start_date: 01/01/1994
